version: "3"

networks:
  webnet:

services:
  nginx:
    image: nginx:1.17.3-alpine
    ports:
      - "8080:80"
    volumes:
      - "./config/site.conf:/etc/nginx/conf.d/default.conf"
      - "./www:/www"
    networks:
      - webnet
      
  php:
    image: php:7-fpm
    volumes:
       - "./www:/www"
    networks:
      - webnet
