version: "3"

services:
  nginx:
    image: nginx:1.17.3-alpine
    ports:
      - "8080:80"
    volumes:
      - "./config/site.conf:/etc/nginx/conf.d/default.conf"
      - "./www:/www"
      
  php:
    image: php7.2-mysql
    volumes:
       - "./www:/www"
      
  mysql:
    image: mysql:5.7.27
    environment:
      - MYSQL_ROOT_PASSWORD=123
      - MYSQL_DATABASE=mydb
      - MYSQL_USER=myuser
      - MYSQL_PASSWORD=secret
    ports:
      - "8081:3306"
    volumes:
      - "./mysqldata:/var/lib/mysql"